def get_hitting_feature_cols(df):
    excluded_cols = [
        "playerID",
        "inducted",
        "nameFirst",
        "nameLast",
        "PitchingTripleCrowns",
        "CyYoungs",
        "RolaidsReliefManAwards",
    ]

    # try_it_out = [
    #     "batting_G",
    #     "batting_AB",
    #     "batting_R",
    #     "batting_H",
    #     "batting_2B",
    #     "batting_3B",
    #     "batting_HR",
    #     "batting_RBI",
    #     "batting_SB",
    #     "batting_CS",
    #     "batting_BB",
    #     "batting_SO",
    #     "batting_IBB",
    #     "batting_HBP",
    #     "batting_SH",
    #     "batting_SF",
    #     "batting_GIDP",
    #     "batting_1B",
    #     "batting_TB",
    #     "batting_PA",
    #     "post_batting_G",
    #     "post_batting_AB",
    #     "post_batting_R",
    #     "post_batting_H",
    #     "post_batting_2B",
    #     "post_batting_3B",
    #     "post_batting_HR",
    #     "post_batting_RBI",
    #     "post_batting_SB",
    #     "post_batting_CS",
    #     "post_batting_BB",
    #     "post_batting_SO",
    #     "post_batting_IBB",
    #     "post_batting_HBP",
    #     "post_batting_SH",
    #     "post_batting_SF",
    #     "post_batting_GIDP",
    #     "post_batting_1B",
    #     "post_batting_TB",
    #     "post_batting_PA",
    # ]

    # try_it_out = [
    #     "batting_G",
    #     "batting_AB",
    #     "batting_R",
    #     "batting_H",
    #     "batting_2B",
    #     "batting_3B",
    #     "batting_HR",
    #     "batting_RBI",
    #     "batting_SB",
    #     "batting_CS",
    #     "batting_BB",
    #     "batting_SO",
    #     "batting_IBB",
    #     "batting_HBP",
    #     "batting_SH",
    #     "batting_SF",
    #     "batting_GIDP",
    #     "batting_1B",
    #     "batting_TB",
    #     "batting_PA",
    #     "post_batting_G",
    #     "post_batting_AB",
    #     "post_batting_R",
    #     "post_batting_H",
    #     "post_batting_2B",
    #     "post_batting_3B",
    #     "post_batting_HR",
    #     "post_batting_RBI",
    #     "post_batting_SB",
    #     "post_batting_CS",
    #     "post_batting_BB",
    #     "post_batting_SO",
    #     "post_batting_IBB",
    #     "post_batting_HBP",
    #     "post_batting_SH",
    #     "post_batting_SF",
    #     "post_batting_GIDP",
    #     "post_batting_1B",
    #     "post_batting_TB",
    #     "post_batting_PA",
    # ]
    # collection = excluded_cols + try_it_out
    # return [col for col in df.columns if col not in collection]
    return [col for col in df.columns if col not in excluded_cols]


def get_pitching_feature_cols(df):
    excluded_cols = [
        "playerID",
        "inducted",
        "nameFirst",
        "nameLast",
        "TripleCrowns",
        "SilverSluggers",
        "BAOpp",
    ]

    # try_it_out = [
    #     "pitching_W",
    #     "pitching_L",
    #     "pitching_G",
    #     "pitching_GS",
    #     "pitching_CG",
    #     "pitching_SHO",
    #     "pitching_SV",
    #     "pitching_IPouts",
    #     "pitching_H",
    #     "pitching_ER",
    #     "pitching_HR",
    #     "pitching_BB",
    #     "pitching_SO",
    #     "pitching_IBB",
    #     "pitching_WP",
    #     "pitching_HBP",
    #     "pitching_BK",
    #     "pitching_BFP",
    #     "pitching_GF",
    #     "pitching_R",
    #     "pitching_SH",
    #     "pitching_SF",
    #     "pitching_GIDP",
    #     "pitching_AB",
    #     "post_pitching_W",
    #     "post_pitching_L",
    #     "post_pitching_G",
    #     "post_pitching_GS",
    #     "post_pitching_CG",
    #     "post_pitching_SHO",
    #     "post_pitching_SV",
    #     "post_pitching_IPouts",
    #     "post_pitching_H",
    #     "post_pitching_ER",
    #     "post_pitching_HR",
    #     "post_pitching_BB",
    #     "post_pitching_SO",
    #     "post_pitching_IBB",
    #     "post_pitching_WP",
    #     "post_pitching_HBP",
    #     "post_pitching_BK",
    #     "post_pitching_BFP",
    #     "post_pitching_GF",
    #     "post_pitching_R",
    #     "post_pitching_SH",
    #     "post_pitching_SF",
    #     "post_pitching_GIDP",
    #     "post_pitching_AB",
    # ]

    # collection = excluded_cols + try_it_out
    # return [col for col in df.columns if col not in collection]
    return [col for col in df.columns if col not in excluded_cols]


def get_label_col():
    return "inducted"
